name: point-eo
channels:
  - conda-forge
  - defaults
dependencies:
  - python

  # DL

  # Geo
  - rasterio
  - geopandas
  - imgaug
  - xarray
  - rioxarray
  - gdal

  # AutoML
  - tpot
  - xgboost

  # DS
  - numpy
  - scipy
  - scikit-learn>=0.22
  - scikit-image
  - pandas>=1.0.0
  - opencv
  - pillow>=6.0.0
  - matplotlib
  - seaborn
  - plotly

  - tqdm
  - numba
  - dask
  - dask-ml
  - joblib

  - streamlit>=1.21

  # ipython + notebooks
  - ipython
  - notebook
  - jupyterlab
  - ipywidgets

  # Testing + linting
  - pylint
  - pytest
  - ruff

  # Others
  - openpyxl
  - cupy
  - pkg-config

  - pip
  - pip:
    - black
    - albumentations
    - pyinstaller