name: point-eo
channels:
  - conda-forge
dependencies:
  - python>=3.10

  # Geo
  - rasterio=1.2.10
  - geopandas
  - xarray
  - rioxarray
  - gdal

  # AutoML
  - tpot
  - xgboost

  # DS
  - numpy
  - scipy
  - scikit-learn>=0.22
  - pandas>=1.0.0
  - matplotlib
  - seaborn

  - tqdm
  - dask
  - joblib